language: erlang

services:
  - docker

otp_release:
   - 22.1
   - 21.0
   - 20.3
   - 19.3
   - 18.3

notifications:
  email: false

install:
   - wget -c https://github.com/erlang/rebar3/releases/download/3.13.1/rebar3 && chmod +x rebar3

script: REBAR=./rebar3 make travis-run
