language: erlang

# Default is 16.04 (xenial) but 18.04 is needed to get TLS 1.3 working
dist: bionic

services:
  - docker

otp_release:
  - 23.0
  - 22.3
  - 22.1
  - 21.2

notifications:
  email: false

install:
   - wget -c https://github.com/erlang/rebar3/releases/download/3.13.1/rebar3 && chmod +x rebar3

script: REBAR=./rebar3 make travis-run
